// Shared response shapes so User/Admin documents are serialized the same
// way everywhere they're returned (auth, admin user management, etc).
export const toPublicUser = (user) => ({
    id: user._id,
    name: user.name,
    email: user.email,
    phone: user.phone,
    status: user.status,
    createdAt: user.createdAt,
});

export const toPublicAdmin = (admin) => ({
    id: admin._id,
    name: admin.name,
    email: admin.email,
    role: admin.role,
});

export const toPublicOrder = (order) => ({
    id: order._id,
    user: order.user,
    items: order.items,
    total: order.total,
    paymentMethod: order.paymentMethod,
    transactionId: order.transactionId,
    screenshotAttached: order.screenshotAttached,
    shipping: order.shipping,
    status: order.status,
    placedAt: order.createdAt,
});

// `image` is duplicated as the first entry of `images` because the app's
// ProductCard reads product.image while the detail gallery reads images[].
export const toPublicProduct = (product) => ({
    id: product._id,
    slug: product.slug,
    name: product.name,
    category: product.category,
    price: product.price,
    stock: product.stock,
    description: product.description,
    image: product.images?.[0],
    images: product.images ?? [],
    rating: product.rating,
    reviews: product.reviewCount,
    reviewCount: product.reviewCount,
    status: product.status,
    // Auto-generated by Product.model.js — the app reads this straight into
    // generateMetadata() and JSON-LD.
    seo: {
        metaTitle: product.seo?.metaTitle,
        metaDescription: product.seo?.metaDescription,
        keywords: product.seo?.keywords ?? [],
        headline: product.seo?.headline,
        imageAlt: product.seo?.imageAlt,
    },
    createdAt: product.createdAt,
    updatedAt: product.updatedAt,
});

export const toPublicBlog = (blog) => ({
    id: blog._id,
    title: blog.title,
    slug: blog.slug,
    category: blog.category,
    author: blog.author,
    excerpt: blog.excerpt,
    content: blog.content ?? [],
    readTime: blog.readTime,
    image: blog.image,
    // The app renders `date` as a plain YYYY-MM-DD string.
    date: blog.publishedAt?.toISOString().slice(0, 10),
    // Full timestamps for Article structured data and sitemap lastModified.
    publishedAt: blog.publishedAt,
    status: blog.status,
    // Auto-generated by Blog.model.js — consumed by the app's generateMetadata.
    seo: {
        metaTitle: blog.seo?.metaTitle,
        metaDescription: blog.seo?.metaDescription,
        keywords: blog.seo?.keywords ?? [],
        imageAlt: blog.seo?.imageAlt,
        wordCount: blog.seo?.wordCount,
    },
    createdAt: blog.createdAt,
    updatedAt: blog.updatedAt,
});

export const toPublicReply = (reply) => ({
    id: reply._id,
    authorType: reply.authorType,
    authorName: reply.authorName,
    message: reply.message,
    createdAt: reply.createdAt,
});

export const toPublicReview = (review) => ({
    id: review._id,
    // Populated documents expose _id; unpopulated ones are the raw ObjectId.
    productId: review.product?._id ?? review.product,
    productName: review.product?.name,
    userId: review.user?._id ?? review.user,
    name: review.userName,
    rating: review.rating,
    comment: review.comment,
    replies: (review.replies ?? []).map(toPublicReply),
    date: review.createdAt?.toISOString().slice(0, 10),
    createdAt: review.createdAt,
});
